version: "3"

services:
  database:
    build: database
    restart: unless-stopped
    ports:
      - "${DATABASE_PUBLISHED_PORT:-20001}:20001"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "DATABASE_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD:-password}"
      - "DATABASE_USER=${DATABASE_USER:-user}"
      - "DATABASE_PASSWORD=${DATABASE_PASSWORD:-password}"
      - "DATABASE_NAME=${DATABASE_NAME:-database}"
    volumes:
      - database:/app/data
  traefik:
    build: traefik
    restart: unless-stopped
    ports:
      - "${TRAEFIK_PUBLISHED_PORT:-20000}:20000"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "TRAEFIK_WEB_HOST=${TRAEFIK_WEB_HOST:-host.docker.internal}"
      - "TRAEFIK_WEB_PORT=${TRAEFIK_WEB_PORT:-20003}"
      - "TRAEFIK_WORDPRESS_HOST=${TRAEFIK_WORDPRESS_HOST:-wordpress}"
      - "TRAEFIK_WORDPRESS_PORT=${TRAEFIK_WORDPRESS_PORT:-80}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  web:
    build: web
    restart: unless-stopped
    network_mode: host
    environment:
      - "WEB_PUBLIC_URL=${WEB_PUBLIC_URL:-http://localhost:20000}"
      - "WEB_WORDPRESS_PUBLIC_URL=${WORDPRESS_PUBLIC_URL:-http://localhost:20000}"
      - "WEB_SURVEYS_API_URL=${WEB_SURVEYS_API_URL:-http://localhost:30000/api}"
    depends_on:
      - wordpress
  wordpress:
    build: wordpress
    restart: unless-stopped
    ports:
      - "${WORDPRESS_PUBLISHED_PORT:-20002}:80"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "WORDPRESS_DATABASE_NAME=${WORDPRESS_DATABASE_NAME:-database}"
      - "WORDPRESS_DATABASE_USER=${WORDPRESS_DATABASE_USER:-user}"
      - "WORDPRESS_DATABASE_PASSWORD=${WORDPRESS_DATABASE_PASSWORD:-password}"
      - "WORDPRESS_DATABASE_HOST=${WORDPRESS_DATABASE_HOST:-database}"
      - "WORDPRESS_DATABASE_PORT=${WORDPRESS_DATABASE_PORT:-20001}"
      - "WORDPRESS_DATABASE_CHARSET=${WORDPRESS_DATABASE_CHARSET:-utf8}"
      - "WORDPRESS_DB_COLLATE=${WORDPRESS_DB_COLLATE:-}"
      - "WORDPRESS_AUTH_KEY=${WORDPRESS_AUTH_KEY:-auth-key}"
      - "WORDPRESS_SECURE_AUTH_KEY=${WORDPRESS_SECURE_AUTH_KEY:-secure-auth-key}"
      - "WORDPRESS_LOGGED_IN_KEY=${WORDPRESS_LOGGED_IN_KEY:-logged-in-key}"
      - "WORDPRESS_NONCE_KEY=${WORDPRESS_NONCE_KEY:-nonce-key}"
      - "WORDPRESS_AUTH_SALT=${WORDPRESS_AUTH_SALT:-auth-salt}"
      - "WORDPRESS_SECURE_AUTH_SALT=${WORDPRESS_SECURE_AUTH_SALT:-secure-auth-salt}"
      - "WORDPRESS_LOGGED_IN_SALT=${WORDPRESS_LOGGED_IN_SALT:-logged-in-salt}"
      - "WORDPRESS_NONCE_SALT=${WORDPRESS_NONCE_SALT:-nonce-salt}"
      - "WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}"
      - "WORDPRESS_DEBUG=${WORDPRESS_DEBUG:-}"
      - "WORDPRESS_CONFIG_EXTRA=${WORDPRESS_CONFIG_EXTRA:-}"
      - "WORDPRESS_PUBLIC_URL=${WORDPRESS_PUBLIC_URL:-http://localhost:20000}"
      - "WORDPRESS_SITE_TITLE=${WORDPRESS_SITE_TITLE:-Radio Aktywne}"
      - "WORDPRESS_ADMIN_USERNAME=${WORDPRESS_ADMIN_USERNAME:-username}"
      - "WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD:-password}"
      - "WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL:-example@example.com}"
      - "WORDPRESS_MAX_UPLOAD_SIZE=${WORDPRESS_MAX_UPLOAD_SIZE:-512M}"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - wordpress:/app/wp-content/uploads
    depends_on:
      - database

volumes:
  database: {}
  wordpress: {}
