/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { DropdownFormFieldOptionTitle } from "./dropdownFormFieldOptionTitle";

export interface DropdownFormFieldOption {
  /** ID of the field option. */
  id: string;
  /** Title of the field option. */
  title?: DropdownFormFieldOptionTitle;
  /** Value of the field option. */
  value: string;
}
