/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormsIdSubmitSubmit422ExtraOneOf } from "./formsIdSubmitSubmit422ExtraOneOf";

export type FormsIdSubmitSubmit422Extra =
  | null
  | FormsIdSubmitSubmit422ExtraOneOf
  | unknown[];
