/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormsIdSubmitSubmit404Extra } from "./formsIdSubmitSubmit404Extra";

/**
 * Not Found Exception
 */
export type FormsIdSubmitSubmit404 = {
  detail: string;
  extra?: FormsIdSubmitSubmit404Extra;
  status_code: number;
};
