/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { CheckboxFormField } from "./checkboxFormField";
import type { DateFormField } from "./dateFormField";
import type { DropdownFormField } from "./dropdownFormField";
import type { EmailFormField } from "./emailFormField";
import type { NumberFormField } from "./numberFormField";
import type { RadioFormField } from "./radioFormField";
import type { SliderFormField } from "./sliderFormField";
import type { TextFormField } from "./textFormField";
import type { TextareaFormField } from "./textareaFormField";
import type { UrlFormField } from "./urlFormField";
import type { YesNoFormField } from "./yesNoFormField";

export type FormFieldsItem =
  | CheckboxFormField
  | DateFormField
  | DropdownFormField
  | EmailFormField
  | NumberFormField
  | RadioFormField
  | SliderFormField
  | TextFormField
  | TextareaFormField
  | UrlFormField
  | YesNoFormField;
