/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormsIdSubmitSubmit422Extra } from "./formsIdSubmitSubmit422Extra";

/**
 * Unprocessable Entity Exception
 */
export type FormsIdSubmitSubmit422 = {
  detail: string;
  extra?: FormsIdSubmitSubmit422Extra;
  status_code: number;
};
