/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormsIdGet404Extra } from "./formsIdGet404Extra";

/**
 * Not Found Exception
 */
export type FormsIdGet404 = {
  detail: string;
  extra?: FormsIdGet404Extra;
  status_code: number;
};
