/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormPagerEntry } from "./formPagerEntry";

/**
 * Entries of the form pager.
 */
export type FormPagerEntries = FormPagerEntry[];
