/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormsList400Extra } from "./formsList400Extra";

/**
 * Validation Exception
 */
export type FormsList400 = {
  detail: string;
  extra?: FormsList400Extra;
  status_code: number;
};
