/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormsIdGet400Extra } from "./formsIdGet400Extra";

/**
 * Validation Exception
 */
export type FormsIdGet400 = {
  detail: string;
  extra?: FormsIdGet400Extra;
  status_code: number;
};
