/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormsIdGet404ExtraOneOf } from "./formsIdGet404ExtraOneOf";

export type FormsIdGet404Extra = null | FormsIdGet404ExtraOneOf | unknown[];
