/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormFieldsItem } from "./formFieldsItem";

/**
 * Fields of the form.
 */
export type FormFields = FormFieldsItem[];
