/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormsIdSubmitSubmit400Extra } from "./formsIdSubmitSubmit400Extra";

/**
 * Validation Exception
 */
export type FormsIdSubmitSubmit400 = {
  detail: string;
  extra?: FormsIdSubmitSubmit400Extra;
  status_code: number;
};
