/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormsList400ExtraOneOf } from "./formsList400ExtraOneOf";

export type FormsList400Extra = null | FormsList400ExtraOneOf | unknown[];
