/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */

export type FormsListParams = {
  /**
   * The maximum number of forms to return.
   */
  limit?: null | number;
  /**
   * The index of the first form to return.
   */
  start?: null | number;
};
