/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormsIdSubmitSubmit404ExtraOneOf } from "./formsIdSubmitSubmit404ExtraOneOf";

export type FormsIdSubmitSubmit404Extra =
  | null
  | FormsIdSubmitSubmit404ExtraOneOf
  | unknown[];
