/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { FormsIdGet400ExtraOneOf } from "./formsIdGet400ExtraOneOf";

export type FormsIdGet400Extra = null | FormsIdGet400ExtraOneOf | unknown[];
