/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { RadioFormFieldOption } from "./radioFormFieldOption";

/**
 * Options of the field.
 */
export type RadioFormFieldOptions = RadioFormFieldOption[];
