/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { SubmissionFields } from "./submissionFields";
import type { SubmissionMetadata } from "./submissionMetadata";

/**
 * The submission for the form.
 */
export interface SubmitRequestSubmission {
  fields: SubmissionFields;
  metadata: SubmissionMetadata;
}
