/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */

/**
 * The confirmation for the submission.
 */
export interface SubmitResponseConfirmation {
  /** ID of the submission. */
  submission: string;
}
