/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { SubmissionMetadataDevice } from "./submissionMetadataDevice";

/**
 * Metadata of the submission.
 */
export interface SubmissionMetadata {
  /** Device of the submission. */
  device?: SubmissionMetadataDevice;
}
