/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { Device } from "./device";

/**
 * Device of the submission.
 */
export type SubmissionMetadataDevice = null | Device;
