/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { SubmitResponseConfirmation } from "./submitResponseConfirmation";

export interface SubmitResponse {
  confirmation: SubmitResponseConfirmation;
}
