/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Fields of the submission.
 */
export interface SubmissionFields {
  [key: string]: unknown;
}
