/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { TextareaFormFieldDefault } from "./textareaFormFieldDefault";
import type { TextareaFormFieldDescription } from "./textareaFormFieldDescription";

export interface TextareaFormField {
  /** Default value of the field. */
  default?: TextareaFormFieldDefault;
  /** Description of the field. */
  description?: TextareaFormFieldDescription;
  /** ID of the field. */
  id: string;
  /** Whether the field is required. */
  required: boolean;
  /** Title of the field. */
  title: string;
  /** Type of the field. */
  type?: string;
}
