/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Default value of the field.
 */
export type TextareaFormFieldDefault = null | string;
