/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { TextFormFieldDefault } from "./textFormFieldDefault";
import type { TextFormFieldDescription } from "./textFormFieldDescription";

export interface TextFormField {
  /** Default value of the field. */
  default?: TextFormFieldDefault;
  /** Description of the field. */
  description?: TextFormFieldDescription;
  /** ID of the field. */
  id: string;
  /** Whether the field is required. */
  required: boolean;
  /** Title of the field. */
  title: string;
  /** Type of the field. */
  type?: string;
}
