/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * api
 * surveys api
 * OpenAPI spec version: 0.1.0
 */
import type { UrlFormFieldDefault } from "./urlFormFieldDefault";
import type { UrlFormFieldDescription } from "./urlFormFieldDescription";

export interface UrlFormField {
  /** Default value of the field. */
  default?: UrlFormFieldDefault;
  /** Description of the field. */
  description?: UrlFormFieldDescription;
  /** ID of the field. */
  id: string;
  /** Whether the field is required. */
  required: boolean;
  /** Title of the field. */
  title: string;
  /** Type of the field. */
  type?: string;
}
